# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: 'https://npm.pkg.github.com'
        scope: '@hetacode'
    - run: sudo npm install -g lerna yarn
    - run: yarn install
    - run: yarn build
    - run: lerna publish from-git --yes --pre-dist-tag next
      env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
